name: PowerMamba
channels:
  - nvidia
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - python=3.10.13
  - cudatoolkit=11.8
  - packaging
  - numpy<2
  - matplotlib
  - pandas
  - scikit-learn
  - pip
  - pip:
      - torch==2.1.1
      - torchvision==0.16.1
      - torchaudio==2.1.1
      - causal-conv1d==1.2.0.post1
      - mamba-ssm==1.2.0.post1
